[package]
name = "greenways-local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
greenways-authority = { path = "../greenways-authority" }
greenways-capabilities = { path = "../greenways-capabilities" }
greenways-identity = { path = "../greenways-identity" }
greenways-protocol = { path = "../greenways-protocol" }
greenways-provider = { path = "../greenways-provider" }
serde_json.workspace = true
zeroize = "1.9.0"

[lints]
workspace = true
