// Packaged Greenways visual-language material for the local Home Node.
export const HOME_NODE_ADMIN_STYLE = `
    :root{--canvas:#f4f2ec;--surface:#fbfaf6;--muted:#e8e8e1;--text:#101612;--quiet:#58615c;--line:rgba(12,59,46,.17);--strong:rgba(12,59,46,.34);--green:#0b6b4f;--gold:#9b7c3e;--danger:#8e3540;--on:#f8fff9;--serif:Didot,"Iowan Old Style",Georgia,serif;--sans:"Avenir Next","Segoe UI",system-ui,sans-serif;--mono:"SFMono-Regular",Consolas,monospace;color-scheme:light}
    :root[data-theme="dark"]{--canvas:#050a08;--surface:#0b1410;--muted:#111e18;--text:#f7f5ef;--quiet:#adb5af;--line:rgba(191,197,192,.18);--strong:rgba(191,197,192,.4);--green:#33a878;--gold:#c8ad73;--danger:#df6874;--on:#04100b;color-scheme:dark}
    *{box-sizing:border-box}html{background:var(--canvas)}body{min-height:100vh;margin:0;color:var(--text);background:linear-gradient(90deg,transparent 49.9%,var(--line) 50%,transparent 50.1%),repeating-linear-gradient(0deg,transparent 0 55px,color-mix(in srgb,var(--line) 52%,transparent) 55px 56px),var(--canvas);font-family:var(--sans);-webkit-font-smoothing:antialiased}
    button{font:inherit;cursor:pointer}button:disabled{cursor:wait;opacity:.5}:focus-visible{outline:3px solid var(--green);outline-offset:3px}.shell{width:min(1040px,calc(100% - 30px));margin:auto}.topbar{min-height:82px;display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:12px}.mark{width:42px;height:42px;position:relative;border:1px solid var(--strong);border-radius:10px;background:var(--surface)}.mark:before,.mark:after{content:"";position:absolute;inset:9px;border:5px solid var(--green);transform:rotate(45deg)}.mark:after{inset:15px;border-color:var(--gold)}.brand strong{display:block;font:400 17px/1 var(--serif)}.brand small,.eyebrow,.section-head p,.metric span,.node-id{font:700 9px/1.4 var(--mono);letter-spacing:.11em;text-transform:uppercase}.brand small{display:block;margin-top:4px;color:var(--quiet)}.theme{width:40px;height:40px;border:1px solid var(--strong);border-radius:8px;color:var(--text);background:var(--surface)}
    .hero{min-height:370px;display:grid;align-content:center;padding:62px 0;border-bottom:1px solid var(--line)}.eyebrow{margin:0;color:var(--gold)}h1{max-width:820px;margin:20px 0 0;font:400 clamp(54px,10vw,96px)/.86 var(--serif);letter-spacing:-.065em}h1 em{color:var(--green);font-weight:400}.lede{max-width:660px;margin:26px 0 0;color:var(--quiet);font-size:14px;line-height:1.7}.trust{display:flex;flex-wrap:wrap;gap:10px 20px;margin-top:30px;padding:14px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);color:var(--quiet);font:650 9px/1.4 var(--mono)}.trust b{color:var(--text)}
    .metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;padding:28px 0}.metric{padding:18px;background:var(--surface);border:1px solid var(--line);border-radius:10px;box-shadow:0 18px 50px rgba(30,43,36,.06)}.metric strong{display:block;font:400 28px/1 var(--serif)}.metric span{display:block;margin-top:8px;color:var(--quiet)}
    .section{padding:34px 0;border-top:1px solid var(--line)}.section-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:16px}.section-head p{margin:0 0 7px;color:var(--gold)}.section-head h2{margin:0;font:400 38px/.98 var(--serif);letter-spacing:-.035em}.section-head>span{color:var(--quiet);font:700 9px var(--mono);text-transform:uppercase}.panel{padding:20px;background:var(--surface);border:1px solid var(--line);border-radius:12px}.pairing{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center}.pairing h3{margin:0;font:400 25px/1 var(--serif)}.pairing p{margin:9px 0 0;color:var(--quiet);font-size:12px;line-height:1.55}.actions{display:flex;gap:8px}.primary,.secondary,.danger{min-height:40px;padding:10px 14px;border-radius:8px;font:700 9px/1 var(--mono);letter-spacing:.04em}.primary{color:var(--on);background:var(--green);border:1px solid color-mix(in srgb,var(--green) 75%,black)}.secondary{color:var(--text);background:transparent;border:1px solid var(--strong)}.danger{color:var(--danger);background:transparent;border:1px solid color-mix(in srgb,var(--danger) 50%,var(--line))}.code{display:none;margin-top:16px;padding:18px;border:1px solid color-mix(in srgb,var(--green) 45%,var(--line));border-radius:10px;background:color-mix(in srgb,var(--green) 7%,var(--surface))}.code[data-visible="true"]{display:flex;align-items:center;justify-content:space-between;gap:18px}.code strong{font:700 clamp(24px,6vw,42px)/1 var(--mono);letter-spacing:.15em}.code small{display:block;margin-top:8px;color:var(--quiet);font:650 9px var(--mono)}
    .list{display:grid;gap:8px}.row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;padding:13px 14px;background:var(--surface);border:1px solid var(--line);border-radius:9px}.dot{width:9px;height:9px;border-radius:50%;background:var(--green);box-shadow:0 0 0 3px color-mix(in srgb,var(--green) 13%,transparent)}.row strong,.row small{display:block}.row strong{font-size:12px}.row small{margin-top:4px;color:var(--quiet);font:600 8px/1.4 var(--mono)}.badge{color:var(--green);font:700 8px var(--mono);letter-spacing:.08em;text-transform:uppercase}.empty{margin:0;padding:22px;color:var(--quiet);border:1px dashed var(--strong);border-radius:9px;font-size:12px;text-align:center}.node-card{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center}.node-card h3{margin:0;font:400 24px/1 var(--serif)}.node-id{margin:8px 0 0;color:var(--quiet);overflow-wrap:anywhere}.notice{min-height:42px;margin:20px 0;padding:12px 14px;color:var(--quiet);background:var(--surface);border-left:3px solid var(--line);font-size:11px;line-height:1.5}.notice[data-tone="good"]{border-left-color:var(--green)}.notice[data-tone="error"]{color:var(--danger);border-left-color:var(--danger)}footer{display:flex;justify-content:space-between;gap:16px;padding:24px 0 36px;border-top:1px solid var(--line);color:var(--quiet);font:700 8px/1.4 var(--mono);letter-spacing:.1em;text-transform:uppercase}
    @media(max-width:720px){.metrics{grid-template-columns:1fr 1fr}.pairing,.node-card{grid-template-columns:1fr}.section-head{align-items:start}.section-head>span{display:none}.code[data-visible="true"]{align-items:flex-start;flex-direction:column}.row{grid-template-columns:auto minmax(0,1fr)}.row .danger{grid-column:2}.actions{flex-wrap:wrap}}
    @media(max-width:430px){.shell{width:min(100% - 24px,1040px)}.hero{min-height:410px}.metrics{grid-template-columns:1fr}.topbar{min-height:72px}h1{font-size:52px}.actions>*{flex:1}.row{padding:12px}.section-head h2{font-size:32px}}
    @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
`;
